version: '3.9'
services:
  discharge_convert_bot:
    build: .
    restart: unless-stopped
    image: discharge_convert_bot
    container_name: discharge_convert_bot_co

networks: 
  default: 
    external: true
    name: autohunt_network       